<?php
/**
 * Magento
 *
 * @category   design_default
 * @package    Flagbit_FeedReader
 * @copyright  Copyright (c) 2010-2011 Flagbit GmbH & Co. KG (http://www.flagbit.de)
 * @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
/* @var $this Flagbit_FeedReader_Block_Abstract */
?>
<?php if($this->getItemCount() > 0): ?>
<div class="block block-feed-reader">
	<div class="block-title">
		<strong><?php echo $this->escapeHtml($this->getTitle()); ?></strong>
	</div>
	<div class="block-content">
		<ol id="feed-items">
		<?php
		$itemCount = 0;
		foreach($this->getItems() as $item): ?>
			<li class="block-feed-item <?php echo (++$itemCount % 2 == 0 ? 'even' : 'odd'); ?><?php if($itemCount == 1): ?> first<?php endif;?><?php if($itemCount >= $this->getItemCount()): ?> last<?php endif; ?>">
				<h5>
					<a href="<?php echo $this->escapeHtml($this->getFeedLink($item)); ?>">
						<?php echo $this->escapeHtml($item->title()); ?>
					</a>
				</h5>
				<p class="date">
					<?php echo Mage::getModel('core/date')->date('d.m.Y H:m', strtotime($this->getFeedPublished($item))); ?>
				</p>
				<p class="summary">
					<a href="<?php echo $this->escapeHtml($this->getFeedLink($item)); ?>">
						<?php echo $this->escapeHtml(Mage::helper('core/string')->truncate(strip_tags($this->getFeedContent($item)), 100, '...', $remainder, false)); ?>
					</a>
				</p>
			</li>
		<?php endforeach; ?>
		</ol>
	</div>
</div>
<?php endif; ?>
